coverage:
  status:
    patch:
      default:
        target: '80'
    project:
      library:
        target: auto
        threshold: 0.1%
        paths:
          - "src/gempakio/.*"

      tests:
        target: 100%
        paths:
          - "tests/.*"

comment: off