name: Testing

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.10', 3.11, 3.12, 3.13, 3.14, 3.15 ]
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install -r ci/requirements.txt  -r ci/test_requirements.txt

      - name: Install gempakIO
        run: |
          python -m pip install .

      - name: Test with pytest
        run: |
          python -m pytest --cov-report json --cov src/gempakio tests

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: pypi-${{ matrix.python-version }}-${{ runner.os }}
          path: coverage.json
          retention-days: 1
  
  codecov:
    name: Codecov Upload
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 2
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          name: ${{ github.workflow }}
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
